@startuml
participant Actor
Actor -> MessageSessionListController : createSession
activate MessageSessionListController
MessageSessionListController -> SessionListService : getIdByUser
activate SessionListService
SessionListService -> SessionListServiceImpl : getIdByUser
activate SessionListServiceImpl
SessionListServiceImpl -> QueryWhere : toUserId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> QueryWhere : userId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> SessionListMapper : findOne
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> SessionListService : insert
activate SessionListService
SessionListService -> SessionListServiceImpl : insert
activate SessionListServiceImpl
SessionListServiceImpl -> SessionListMapper : insert
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> SessionListService : getIdByUser
activate SessionListService
SessionListService -> SessionListServiceImpl : getIdByUser
activate SessionListServiceImpl
SessionListServiceImpl -> QueryWhere : toUserId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> QueryWhere : userId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> SessionListMapper : findOne
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> UserService : getUserById
activate UserService
UserService -> UserServiceImpl : getUserById
activate UserServiceImpl
UserServiceImpl -> UserQuery : where
activate UserQuery
UserQuery --> UserServiceImpl
deactivate UserQuery
UserServiceImpl -> QueryWhere : userId
activate QueryWhere
QueryWhere --> UserServiceImpl
deactivate QueryWhere
UserServiceImpl -> UserMapper : findOne
activate UserMapper
UserMapper --> UserServiceImpl
deactivate UserMapper
UserServiceImpl --> UserService
deactivate UserServiceImpl
UserService --> MessageSessionListController
deactivate UserService
MessageSessionListController -> SessionListService : insert
activate SessionListService
SessionListService -> SessionListServiceImpl : insert
activate SessionListServiceImpl
SessionListServiceImpl -> SessionListMapper : insert
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> SessionListService : getIdByUser
activate SessionListService
SessionListService -> SessionListServiceImpl : getIdByUser
activate SessionListServiceImpl
SessionListServiceImpl -> QueryWhere : toUserId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> QueryWhere : userId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> SessionListMapper : findOne
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> SessionListService : getSessionListById
activate SessionListService
SessionListService -> SessionListServiceImpl : getSessionListById
activate SessionListServiceImpl
SessionListServiceImpl -> SessionListMapper : findById
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> SessionListService : getSessionListById
activate SessionListService
SessionListService -> SessionListServiceImpl : getSessionListById
activate SessionListServiceImpl
SessionListServiceImpl -> SessionListMapper : findById
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> Result : success
activate Result
Result --> MessageSessionListController
deactivate Result
return



Actor -> MessageSessionListController : delSession
activate MessageSessionListController
MessageSessionListController -> SessionListService : deleteById
activate SessionListService
SessionListService -> SessionListServiceImpl : deleteById
activate SessionListServiceImpl
SessionListServiceImpl -> SessionListMapper : deleteById
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> Result : success
activate Result
Result --> MessageSessionListController
deactivate Result
return
 


Actor -> MessageSessionListController : sessionListAlready
activate MessageSessionListController
MessageSessionListController -> SessionListService : getSessionListByUserId
activate SessionListService
SessionListService -> SessionListServiceImpl : getSessionListByUserId
activate SessionListServiceImpl
SessionListServiceImpl -> SessionListQuery : where
activate SessionListQuery
SessionListQuery --> SessionListServiceImpl
deactivate SessionListQuery
SessionListServiceImpl -> QueryWhere : userId
activate QueryWhere
QueryWhere --> SessionListServiceImpl
deactivate QueryWhere
SessionListServiceImpl -> SessionListMapper : listEntity
activate SessionListMapper
SessionListMapper --> SessionListServiceImpl
deactivate SessionListMapper
SessionListServiceImpl --> SessionListService
deactivate SessionListServiceImpl
SessionListService --> MessageSessionListController
deactivate SessionListService
MessageSessionListController -> Result : success
activate Result
Result --> MessageSessionListController
deactivate Result
return
@enduml


@enduml